instance: instance-${instance}
lmdbs:
  main:
    path: /lmdb/instance-${instance}/db
    dupsort_hack: true
    options:
      no_subdir: true
      create: true
  shard:
    path: /lmdb/instance-${instance}/db-0
    options:
      no_subdir: true
      create: true

storage:
  #type: fs
  type: s3
  options:
    #root_path: /snapshots
    access_key: minioadmin
    secret_key: minioadmin
    region: us-east-1
    bucket: lightningstream
    endpoint_url: http://minio:9000

http:
  address: ":8500"

