instance: instance-${instance}
lmdbs:
  main:
    path: /lmdb/instance-${instance}/db
    dupsort_hack: true
    options:
      no_subdir: true
      create: true
    dbi_options:
      # WARNING: Only added because old snapshots are missing the flags,
      #          only add when you are sure you need this.
      pdns:
        override_create_flags: 0
      domains:
        override_create_flags: MDB_INTEGERKEY
      domains_0:
        override_create_flags: MDB_DUPSORT|MDB_DUPFIXED
      keydata:
        override_create_flags: MDB_INTEGERKEY
      keydata_0:
        override_create_flags: MDB_DUPSORT|MDB_DUPFIXED
      metadata:
        override_create_flags: MDB_INTEGERKEY
      metadata_0:
        override_create_flags: MDB_DUPSORT|MDB_DUPFIXED
      tsig:
        override_create_flags: MDB_INTEGERKEY
      tsig_0:
        override_create_flags: MDB_DUPSORT|MDB_DUPFIXED
  shard:
    path: /lmdb/instance-${instance}/db-0
    options:
      no_subdir: true
      create: true
    dbi_options:
      # WARNING: Only added because old snapshots are missing the flags,
      #          only add when you are sure you need this.
      records:
        override_create_flags: 0

storage:
  #type: fs
  type: s3
  options:
    #root_path: /snapshots
    access_key: minioadmin
    secret_key: minioadmin
    region: us-east-1
    bucket: lightningstream
    endpoint_url: http://minio:9000
  cleanup:
    enabled: true
    interval: 15m
    must_keep_interval: 24h
    remove_old_instances_interval: 168h

http:
  address: ":8500"

# log:
#   level: info

# health:
#   storage_list:
#     warn_duration: 5s
#     error_duration: 15s
#     interval: 1s
#   storage_load:
#     warn_duration: 5s
#     error_duration: 15s
#     interval: 1s
#   storage_store:
#     warn_duration: 5s
#     error_duration: 15s
#     interval: 1s
#   start:
#     warn_duration: 5s
#     error_duration: 15s
#     report_healthz: true
#     report_metadata: true
#     interval: 1s